import image1 from '../assets/images/dp.jpg'
import image2 from '../assets/images/dp2.jpg'
import image3 from '../assets/images/dp3.jpg'
import image4 from '../assets/images/dp4.jpg'
import image5 from '../assets/images/dp5.jpg'


export const feedData = [
    {
        id: 1,
        tweetImg:  image5,
        name: 'Kounde',
        verified: null,
        tweet: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime against food?",
        time: '51m',
        replyImg1: image4,
        replyImg2: image1,
        replies: 26,
        likes: 421,
        featuredImg: image3,
        featuredComment: null,
        featuredReplies: 91,
        featuredLikes: 220,
    },
    {
        id: 2,
        tweetImg:  image4,
        name: 'Basit Akande',
        verified: 'verified',
        tweet: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime against food?",
        time: '51m',
        replyImg1: image2,
        replyImg2: image3,
        replies: 26,
        likes: 421,
        featuredImg: image3,
        featuredComment: "You can say that again and again. Sweet memory ever!",
        featuredReplies: 91,
        featuredLikes: 220,
    },
    {
        id: 3,
        tweetImg:  image1,
        name: 'Sam kerr',
        verified: null,
        tweet: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime against food?",
        time: '51m',
        replyImg1: image1,
        replyImg2: image4,
        replies: 26,
        likes: 421,
        featuredImg: image3,
        featuredComment: null,
        featuredReplies: 91,
        featuredLikes: 220,
    },
    {
        id: 4,
        tweetImg:  image3,
        name: 'Karen',
        verified: null,
        tweet: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime against food?",
        time: '51m',
        replyImg1: image1,
        replyImg2: image4,
        replies: 26,
        likes: 421,
        featuredImg: image3,
        featuredComment: null,
        featuredReplies: 91,
        featuredLikes: 220,
    },
    {
        id: 5,
        tweetImg:  image2,
        name: 'John Altman',
        verified: 'verified',
        tweet: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime against food?",
        time: '51m',
        replyImg1: image1,
        replyImg2: image4,
        replies: 26,
        likes: 421,
        featuredImg: image3,
        featuredComment: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime",
        featuredReplies: 91,
        featuredLikes: 220,
    },
    {
        id: 6,
        tweetImg:  image1,
        name: 'pretty Cath',
        verified: null,
        tweet: "I'm having a debate with my friends is pineapple on pizza acceptable or a crime against food?",
        time: '51m',
        replyImg1: image1,
        replyImg2: image4,
        replies: 26,
        likes: 421,
        featuredImg: image3,
        featuredComment: null,
        featuredReplies: 91,
        featuredLikes: 220,
    },
]